name: K6 Performance Test

on:
  push:
    branches:
      - main

jobs:
  k6_load_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -L | tar xvz
          sudo cp k6-v0.49.0-linux-amd64/k6 /usr/local/bin

      - name: Run k6 test
        env:
          K6_CLOUD_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
        run: k6 run --out cloud k6/test.js